pub(crate) mod base_value_object;
pub(crate) mod proxmox_csrf_token;
pub(crate) mod proxmox_host;
pub(crate) mod proxmox_password;
pub(crate) mod proxmox_port;
pub(crate) mod proxmox_realm;
pub(crate) mod proxmox_ticket;
pub(crate) mod proxmox_uri;
pub(crate) mod proxmox_username;
